import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';

// import festa from '../../public/assets/festa.svg';
import { Header } from '../components/Header';
import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Image src={festa} alt="logo" width={200} height={200} /> */}
        <Header />
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/eduardor2m/ticket">
          Desenvolved by Eduardo Melo
        </a>
      </footer>
    </div>
  );
};

export default Home;
